language: python
os: linux
python:
- '3.6'
- '3.7'
install: "pip install -r requirements.txt"
script: "pytest test.py"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: $PYPI_TOKEN
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
