deploy:
  provider: pypi
  user: __token__
  password:
    secure: bb6FcVUgIYkO12qplaEOqGUV3KLXRIAaOb8ELBITCHkGetEJbLxTyrecQbb+K7l9BAPNsV84ruLb1ZF3HIj7rlfvwjlLgTkCNOb3vty+QHEjz3avxr5bsi10CKPCajGwrvKXwDW3I3YRqCPXG/igcqqxMdVTfoJKtxeD0uBjo64eay85IBcsyVUPQGn08223JxtRqS7hNa5TeQA0gjkGTdEeF1qjI519d7zz5VQZsf+bbUwh63sXdTxrlawnR0DtzH3mS3vmdW5nwejH1HrpctTREdm9vgU13KiWWxFpmaKEa809r5mhcuz/g1qxFjvRtmymJok5t7qAT0b4kXWwgr5bYLM6CrCG9Gkd6gbQEHxiy5OczfOVN+mwp9Pt4GqJcJoVZ7p78TRIZRdOFoY7yCrZwtwOdjtsljuPCjshRsNiwubzEgWG/R173GT9pIFxAhWW4OTuiUEPtvz7ORzFNiVeZnIe5vlo99kV6asDGzjtULTq8lR49gDEF88j9rsVj2R22ai3w+LI5yqz+I2lYaFayaT0ZZ42pMYT5c/zhkcPKSR8d6pydp1OGnJI2reEN2xHm3fBV4yKiiqBu1+PjnBfEUmniPJ2cGHq4+8pX6fr70RB5cfo0YgAREqUA2zEuRyZKa7HhKIesKPJ6cmrwm6hSzMmOInC8fWbBf6+LF4=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
